language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
env:
  - "HARNESS_OPTIONS=j9 MOJO_MAIL_TEST=1 PMLTQ_SERVER_TESTDB='mongodb://127.0.0.1:27017/pmltq-server-test'"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://repo.mongodb.org/apt/ubuntu '$(lsb_release -sc)'/mongodb-org/3.0 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "cpanm -n Devel::Cover::Report::Coveralls"
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script: "HARNESS_PERL_SWITCHES='-MDevel::Cover' ./script/pmltq-server test && cover -report coveralls"
notifications:
  email:
    recipients:
      - sedlakmichal@gmail.com
