language: perl
sudo: false

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env:
  - MOJO_MAIL_TEST=1 PG_PORT=5432

branches:
  only:
    - master
    - treebank_priv
    - tb_help
    - multiple_ids
    - fix_suggest

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton

install:
  - carton install

before_script:
  - psql -c 'create database test;' -U postgres
  - pg_restore -d test -U postgres --no-acl --no-owner -w t/test_files/pdt20_mini/pdt20_mini.dump

script: "HARNESS_PERL_SWITCHES='-MDevel::Cover=+ignore,local,^t/' carton exec ./script/pmltq-server test"

after_success:
  - cover -report coveralls

notifications:
  email:
    recipients:
      - sedlakmichal@gmail.com
    on_success: change
    on_failure: always

cache:
  directories:
    - local

before_cache:
  - rm -f local/cache/modules/02packages.details.txt

addons:
  postgresql: "9.3"
