language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
env:
  - "HARNESS_OPTIONS=j9 PMLTQ_SERVER_TESTDB='mongodb://127.0.0.1:27017/pmltq-server-test'"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script: "./script/pmltq-server test"
